# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/r5xQ/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter RMX1911 RMX2030,$(TARGET_DEVICE)),)

endif
